DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	ID number PRIMARY KEY,
	EMAIL VARCHAR2(255) UNIQUE,
	PASSWORD VARCHAR2(100),
	NAME VARCHAR(100),
	REGDATE date
);


CREATE SEQUENCE MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1;
	

CREATE OR REPLACE TRIGGER TRI_MEMBER_ID_SEQ
BEFORE INSERT ON MEMBER FOR EACH ROW
BEGIN 
	IF Inserting AND :NEW.ID IS NULL THEN 
		SELECT MEMBER_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END IF;
END;
